In [2]:
%pip install polars
import polars as pl
from pathlib import Path

Requirement already satisfied: polars in /opt/miniconda3/lib/python3.14/site-packages (1.44.2)
Requirement already satisfied: polars-runtime-32==1.44.2 in /opt/miniconda3/lib/python3.14/site-packages (from polars) (1.44.2)
Note: you may need to restart the kernel to use updated packages.

In [5]:
data_dir = Path.cwd().parent / "assets"
year_2025_data = data_dir / "TTC Subway Delay Data since 2025.csv"

In [9]:
df = pl.read_csv(year_2025_data)
df.glimpse()

Rows: 40656
Columns: 11
$ _id       <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ Date      <str> '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01'
$ Time      <str> '02:10', '02:30', '02:32', '02:58', '02:58', '07:59', '08:13', '08:15', '09:14', '09:22'
$ Day       <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ Station   <str> 'BATHURST STATION', 'DUNDAS STATION', 'BROADVIEW STATION', 'KEELE STATION', 'COXWELL STATION', 'DONLANDS STATION', 'BLOOR STATION', 'BLOOR STATION', 'FINCH STATION', 'BATHURST STATION'
$ Code      <str> 'MUSAN', 'MUIRS', 'PUMST', 'EUSC', 'SUAE', 'TUNOA', 'PUTR', 'PUTR', 'SUDP', 'SUUT'
$ Min Delay <i64> 5, 0, 0, 0, 0, 5, 9, 5, 0, 0
$ Min Gap   <i64> 9, 0, 0, 0, 0, 10, 0, 0, 0, 0
$ Bound     <str> 'E', null, 'E', 'W', null, 'W', 'S', 'N', 'S', 'E'
$ Line      <str> 'BD', 'YU', 'BD', 'BD', 'BD', 'BD', 'YU', 'YU', 'YU', 'BD'
$ Vehicle   <i64> 5227, 0, 0, 5293, 0, 5000, 5836, 5706, 5596, 5312

In [11]:
df.null_count()

shape: (1, 11)
┌─────┬──────┬──────┬─────┬───┬─────────┬───────┬──────┬─────────┐
│ _id ┆ Date ┆ Time ┆ Day ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ --- ┆ ---  ┆ ---  ┆ --- ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ u32 ┆ u32  ┆ u32  ┆ u32 ┆   ┆ u32     ┆ u32   ┆ u32  ┆ u32     │
╞═════╪══════╪══════╪═════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 0   ┆ 0    ┆ 0    ┆ 0   ┆ … ┆ 0       ┆ 14179 ┆ 143  ┆ 0       │
└─────┴──────┴──────┴─────┴───┴─────────┴───────┴──────┴─────────┘

In [13]:
df.schema

(Schema([('_id', Int64),
         ('Date', String),
         ('Time', String),
         ('Day', String),
         ('Station', String),
         ('Code', String),
         ('Min Delay', Int64),
         ('Min Gap', Int64),
         ('Bound', String),
         ('Line', String),
         ('Vehicle', Int64)]),
 (40656, 11))

In [14]:
df

shape: (40_656, 11)
┌───────┬────────────┬───────┬───────────┬───┬─────────┬───────┬──────┬─────────┐
│ _id   ┆ Date       ┆ Time  ┆ Day       ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---   ┆ ---        ┆ ---   ┆ ---       ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ i64   ┆ str        ┆ str   ┆ str       ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞═══════╪════════════╪═══════╪═══════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 1     ┆ 2025-01-01 ┆ 02:10 ┆ Wednesday ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5227    │
│ 2     ┆ 2025-01-01 ┆ 02:30 ┆ Wednesday ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 3     ┆ 2025-01-01 ┆ 02:32 ┆ Wednesday ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 0       │
│ 4     ┆ 2025-01-01 ┆ 02:58 ┆ Wednesday ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5293    │
│ 5     ┆ 2025-01-01 ┆ 02:58 ┆ Wednesday ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …     ┆ …          ┆ …     ┆ …         ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 40652 ┆ 2026-06-30 ┆ 01:37 ┆ Tuesday   ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 40653 ┆ 2026-06-30 ┆ 17:57 ┆ Tuesday   ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│ 40654 ┆ 2026-06-30 ┆ 18:53 ┆ Tuesday   ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 40655 ┆ 2026-06-30 ┆ 21:04 ┆ Tuesday   ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│ 40656 ┆ 2026-06-30 ┆ 21:26 ┆ Tuesday   ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
└───────┴────────────┴───────┴───────────┴───┴─────────┴───────┴──────┴─────────┘

In [16]:
df["Min Delay"].mean()

2.782910271546635